import React,{useEffect,useState} from 'react';
import {Modal,View,Text,TextInput,Pressable,KeyboardAvoidingView,Platform} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
export function MapConnection({open,api,onClose,onSave}:{open:boolean;api:string;onClose:()=>void;onSave:(api:string,token:string)=>Promise<void>}){
 const [url,setUrl]=useState(api),[token,setToken]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const insets=useSafeAreaInsets();
 useEffect(()=>{if(open){setUrl(api);setToken('');setError('')}},[open,api]);
 const connect=async()=>{setBusy(true);setError('');try{const address=new URL(url.trim());if(address.username||address.password||address.search||address.hash||address.pathname!=='/')throw Error('Use the server origin only, such as https://maps.example.com');if(address.protocol!=='https:'&&(address.protocol!=='http:'||token.trim()))throw Error('An access key requires HTTPS. Local HTTP servers can use a blank key.');const next=address.origin;const response=await fetch(next+'/metadata',{headers:token.trim()?{Authorization:'Bearer '+token.trim()}:{},signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error(response.status===401?'Invalid map access key.':response.status===429?'Map allowance reached.':'Server unavailable ('+response.status+').');const info=await response.json();if(!info.datasetId)throw Error('This is not a map server.');await onSave(next,token.trim())}catch(e){setError(String(e))}finally{setBusy(false)}};
 return <Modal visible={open} animationType="slide" onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1,padding:24,paddingTop:insets.top+24,backgroundColor:'#fafbf5',gap:16}}><Text style={{fontSize:24,fontWeight:'600'}}>Map server</Text><Text>Connect to your cloud maps. Your access key is stored securely on this phone.</Text><TextInput accessibilityLabel="Map server URL" value={url} onChangeText={setUrl} autoCapitalize="none" autoCorrect={false} keyboardType="url" style={{padding:14,borderWidth:1,borderColor:'#acbbaa',borderRadius:8}}/><TextInput accessibilityLabel="Map access key" placeholder="Access key (blank for local server)" value={token} onChangeText={setToken} autoCapitalize="none" autoCorrect={false} secureTextEntry style={{padding:14,borderWidth:1,borderColor:'#acbbaa',borderRadius:8}}/>{!!error&&<Text accessibilityRole="alert">{error}</Text>}<Pressable disabled={busy} onPress={connect} style={{padding:16,backgroundColor:'#dbe9d4',borderRadius:8}}><Text>{busy?'Connecting…':'Connect'}</Text></Pressable><Pressable disabled={busy} onPress={onClose} style={{padding:16}}><Text>Close</Text></Pressable></KeyboardAvoidingView></Modal>
}
