import React from 'react';
import {Alert,Modal,Pressable,StyleSheet,Switch,ScrollView,Text,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import type {GPSRecording} from './gpsRecording';
export function RecordingStats({open,onClose,recording,gpsStatus,backgroundEnabled,backgroundBusy,backgroundMessage,onBackgroundChange}:{open:boolean;onClose:()=>void;recording:GPSRecording;gpsStatus:string;backgroundEnabled:boolean;backgroundBusy:boolean;backgroundMessage:string;onBackgroundChange:(value:boolean)=>void}){
 const insets=useSafeAreaInsets(),s=recording.stats,minutes=Math.floor(s.movingTime/60),time=Math.floor(minutes/60)+':'+String(minutes%60).padStart(2,'0')+':'+String(Math.floor(s.movingTime)%60).padStart(2,'0');
 return <Modal visible={open} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><Pressable style={StyleSheet.absoluteFill} onPress={onClose} accessibilityLabel="Close recording stats"/><ScrollView style={{maxHeight:"90%",flexGrow:0}} contentContainerStyle={[styles.sheet,{paddingBottom:insets.bottom+20,marginLeft:insets.left,marginRight:insets.right}]}><View style={styles.heading}><Text style={styles.title}>Current recording</Text><Pressable onPress={onClose} accessibilityRole="button" accessibilityLabel="Close stats" style={styles.button}><Text>✕</Text></Pressable></View><Text style={styles.note}>{recording.ready?gpsStatus:'Recalculating from saved points…'}</Text><View style={styles.stats}>{[['Distance',(s.distance/1609.344).toFixed(2)+' mi'],['Moving time',time],['Elevation gain',Math.round(s.elevationGain*3.28084)+' ft']].map(([label,value])=><View key={label} style={styles.stat}><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></View>)}</View>{!!recording.error&&<Text accessibilityRole="alert" style={styles.error}>{recording.error}</Text>}<View style={styles.background}><View style={{flex:1}}><Text style={styles.label}>Record in background</Text><Text style={styles.note}>{backgroundBusy?'Updating location permissions…':backgroundEnabled?'Continues with the screen locked.':'Keep recording when you leave the app. Requires Always / Allow all the time location access.'}</Text></View><Switch accessibilityLabel="Record GPS in background" value={backgroundEnabled} disabled={backgroundBusy} onValueChange={onBackgroundChange} trackColor={{true:'#287259'}}/></View>{!!backgroundMessage&&<Text style={styles.error}>{backgroundMessage}</Text>}<View style={styles.actions}><Pressable disabled={!recording.ready} accessibilityRole="button" style={styles.button} onPress={()=>void recording.recalculate()}><Text>Recalculate from file</Text></Pressable><Pressable accessibilityRole="button" style={styles.button} onPress={()=>Alert.alert('Reset recording?','This clears the current GPS points and all three stats.',[{text:'Cancel',style:'cancel'},{text:'Reset',style:'destructive',onPress:()=>recording.reset()}])}><Text style={styles.error}>Reset</Text></Pressable></View></ScrollView></View></Modal>
}
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:'#18342655',justifyContent:'flex-end'},sheet:{backgroundColor:'#fafbf5',borderTopLeftRadius:20,borderTopRightRadius:20,padding:20},heading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:20,fontWeight:'600',color:'#234234'},note:{color:'#617264',fontSize:12,marginBottom:18},stats:{flexDirection:'row',gap:8},stat:{flex:1},value:{fontSize:22,fontWeight:'600',color:'#234234'},label:{fontSize:12,color:'#617264',marginTop:5},background:{flexDirection:"row",alignItems:"center",gap:16,marginTop:24},actions:{flexDirection:'row',justifyContent:'space-between',marginTop:24,gap:8},button:{minHeight:44,padding:12,justifyContent:'center',backgroundColor:'#e4ece0',borderRadius:10},error:{color:'#983f36',marginTop:8}});
