#!/usr/bin/env python3
"""Rebuild offline POI helpers from pinned Maki and original topographic SVGs."""
from pathlib import Path
import json
import xml.etree.ElementTree as ET

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
manifest = json.loads((HERE/'source.json').read_text())
paths = {}
for entry in manifest['icons']:
    svg = ET.parse(HERE/entry['file']).getroot()
    if svg.get('viewBox') not in ('0 0 15 15', None):
        raise ValueError('Unexpected Maki viewBox')
    values = []
    for element in svg.iter():
        if any(element.get(attr) for attr in ('transform','clip-path','fill-rule','clip-rule','style','stroke','fill')):
            raise ValueError('Transformed or styled SVG paths need explicit support')
        if element.tag.rsplit('}',1)[-1] == 'path':
            values.append(element.attrib['d'])
    if not values:
        raise ValueError('Missing SVG paths')
    paths[entry['name']] = values

# Original topographic symbols complement, but do not modify, vendored Maki.
topo = json.loads((REPO/'assets/topo-icons/symbols.json').read_text())
for name in topo['icons']:
    paths[name] = [e.attrib['d'] for e in ET.parse(REPO/'assets/topo-icons'/f'{name}.svg').getroot().iter() if e.tag.endswith('path')]
kinds = topo['kinds']
body = '''
function installPoiImages(map) {
  map.__topoPoiIcon = p => {
    const kind = p.kind || p.class, icon = TOPO_KINDS[kind];
    if (!icon) return null;
    const symbol = kind === 'waterfall' && /cascade/i.test(p.name || '') ? 'cascade' : icon;
    return 'poi-' + (kind === 'shelter' ? 'square' : 'circle') + '-' + symbol;
  };
  function add(id) {
    const match = /^poi-(square|circle)-(.+)$/.exec(id);
    if (!match || !POI_PATHS[match[2]] || map.hasImage(id)) return;
    const started=Date.now();
    const canvas = document.createElement('canvas');
    canvas.width = 48; canvas.height = 48;
    const ctx = canvas.getContext('2d', {willReadFrequently:true});
    if (!ctx) throw new Error('Canvas is required for POI icons');
    ctx.beginPath();
    if (match[1] === 'circle') ctx.arc(24,24,21,0,Math.PI*2);
    else {
      ctx.moveTo(8,3);ctx.lineTo(40,3);ctx.quadraticCurveTo(45,3,45,8);
      ctx.lineTo(45,40);ctx.quadraticCurveTo(45,45,40,45);ctx.lineTo(8,45);
      ctx.quadraticCurveTo(3,45,3,40);ctx.lineTo(3,8);ctx.quadraticCurveTo(3,3,8,3);ctx.closePath();
    }
    ctx.fillStyle = '#fffdf5'; ctx.fill();
    ctx.strokeStyle = '#6b806e'; ctx.lineWidth = 1.6; ctx.stroke();
    ctx.save();ctx.translate(9,9);ctx.scale(2,2);ctx.fillStyle = ['waterfall','cascade','spring'].includes(match[2]) ? '#397e9d' : '#304e3b';
    for (const path of POI_PATHS[match[2]]) ctx.fill(new Path2D(path));
    ctx.restore();
    map.addImage(id,ctx.getImageData(0,0,48,48),{pixelRatio:2});
    const stats=map.__topoIconStats||(map.__topoIconStats={count:0,totalMs:0,maxMs:0});const ms=Date.now()-started;stats.count++;stats.totalMs+=ms;stats.maxMs=Math.max(stats.maxMs,ms);
  }
  map.__topoEnsurePoiImage=add;
  map.on('styleimagemissing',event=>add(event.id));
}
'''
plain = '// Pinned Maki CC0 paths plus original artwork in assets/topo-icons.\nconst POI_PATHS = '+json.dumps(paths,separators=(',',':'))+';\nconst TOPO_KINDS = '+json.dumps(kinds,separators=(',',':'))+';\n'+body
mobile = '// Generated by assets/maki/build-icons.py. Literal source is safe across Hermes and WebView.\nexport const poiImagesScript = '+json.dumps(plain)+';\n'
web = plain.replace('const POI_PATHS =','const POI_PATHS: Record<string,string[]> =').replace('function installPoiImages(map)',"export function installPoiImages(map: import('maplibre-gl').Map)").replace('function add(id)','function add(id: string)').replace("const ctx = canvas.getContext('2d', {willReadFrequently:true});","const ctx = canvas.getContext('2d', {willReadFrequently:true})!;")
web = web.replace('map.__topoPoiIcon = p =>', '(map as any).__topoPoiIcon = (p:any) =>').replace('const TOPO_KINDS =', 'const TOPO_KINDS: Record<string,string> =')
web=web.replace('map.__topoEnsurePoiImage','(map as any).__topoEnsurePoiImage').replace('map.__topoIconStats','(map as any).__topoIconStats')
(REPO/'apps/mobile/src/poiImages.ts').write_text(mobile)
(REPO/'apps/web/app/poiImages.ts').write_text('// Generated by assets/maki/build-icons.py.\n'+web)

# Keep the icon expression identical in all style entry points, including offline.
expression=['match',['coalesce',['get','kind'],['get','class'],'']]
for kind,icon in kinds.items():
    value='poi-'+('square' if kind=='shelter' else 'circle')+'-'+icon
    if kind=='waterfall':value=['case',['in','cascade',['downcase',['coalesce',['get','name'],'']]],'poi-circle-cascade',value]
    expression.extend([kind,value])
for file in ['apps/web/app/vectorStyle.ts','apps/mobile/src/vectorStyle.ts','apps/mobile/src/style.mjs']:
    path=REPO/file;text=path.read_text();start='// BEGIN GENERATED NATURAL SYMBOLS';end='// END GENERATED NATURAL SYMBOLS'
    block=start+'\nconst NATURAL_POI_MATCH = '+json.dumps(expression,separators=(',',':'))+';\n'+end
    if start in text:
        a=text.index(start);b=text.index(end,a)+len(end);text=text[:a]+block+text[b:]
    else:
        text+='\n'+block+'\n'
        at=text.rindex(' return style;')
        code=" for(const layer of style.layers){if(layer.type==='symbol'&&(layer.source==='recreation'||layer.source==='osm'&&layer['source-layer']==='poi'))layer.layout['icon-image']=[...NATURAL_POI_MATCH,layer.layout['icon-image']];}\n"
        text=text[:at]+code+text[at:]
    path.write_text(text)
