import fs from 'node:fs';import {createRequire} from 'node:module';
const req=createRequire(new URL('../apps/web/package.json',import.meta.url));const {build}=req('esbuild');
const result=await build({entryPoints:[new URL('../apps/mobile/src/terrain.worker.ts',import.meta.url).pathname],bundle:true,write:false,platform:'browser',format:'iife',target:'es2020',minify:true,legalComments:'inline'});
const code=result.outputFiles[0].text;
for(const dir of ['apps/mobile/src','apps/web/app'])fs.writeFileSync(new URL('../'+dir+'/terrainWorkerSource.ts',import.meta.url),'// Generated by scripts/build-terrain.mjs; bundled offline contour worker.\nexport const terrainWorkerSource='+JSON.stringify(code)+';\n');
console.log('Contour worker',code.length,'bytes');
