import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
let serial=0;
async function setup({expoGo=false,permission=true,registered=false,waitForInit=null}={}){
 const received=[],calls=[],recording={flush(){calls.push('flush')},breakSegment(){calls.push('break')}};let handler;
 globalThis.__backgroundTaskManager={isAvailableAsync:async()=>true,defineTask:(name,fn)=>{assert.equal(name,'topo-map-background-gps-v1');handler=fn}};
 globalThis.__backgroundLocation={Accuracy:{High:4},ActivityType:{Fitness:3},hasStartedLocationUpdatesAsync:async()=>registered,requestForegroundPermissionsAsync:async()=>({granted:permission}),requestBackgroundPermissionsAsync:async()=>({granted:permission}),hasServicesEnabledAsync:async()=>true,startLocationUpdatesAsync:async(name,options)=>{calls.push(options);registered=true},stopLocationUpdatesAsync:async()=>{calls.push('stop');registered=false}};
 globalThis.__backgroundConstants={executionEnvironment:expoGo?'storeClient':'standalone'};
 globalThis.__backgroundRecording={currentRecording:()=>recording,initializeRecording:async()=>{if(waitForInit)await waitForInit;return recording},recordLocation:p=>received.push(p.timestamp)};
 const code=ts.transpileModule(fs.readFileSync(new URL('../src/backgroundLocation.ts',import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace(/import \* as TaskManager from 'expo-task-manager';/,'const TaskManager=globalThis.__backgroundTaskManager;').replace(/import \* as Location from 'expo-location';/,'const Location=globalThis.__backgroundLocation;').replace(/import Constants from 'expo-constants';/,'const Constants=globalThis.__backgroundConstants;').replace(/import .*?from '.\/gpsService';/,'const {currentRecording,initializeRecording,recordLocation}=globalThis.__backgroundRecording;');
 const service=await import('data:text/javascript;base64,'+Buffer.from(code+'\n//'+serial++).toString('base64'));return {service,calls,received,handler:args=>handler(args)};
}
test('Expo Go shows an actionable build requirement without starting background GPS',async()=>{const t=await setup({expoGo:true});await t.service.refreshBackgroundRecording();assert.equal(t.service.backgroundRecordingEnabled(),false);await assert.rejects(t.service.setBackgroundRecording(true),/development build/);assert.deepEqual(t.calls,[])});
test('permission denial leaves background recording off',async()=>{const t=await setup({permission:false});await assert.rejects(t.service.setBackgroundRecording(true),/foreground location/);assert.equal(t.service.backgroundRecordingEnabled(),false);assert.deepEqual(t.calls,[])});
test('opt-in service records sorted batches, flushes, and stops accepting late deliveries when disabled',async()=>{
 const t=await setup();await t.service.setBackgroundRecording(true);assert.equal(t.service.backgroundRecordingEnabled(),true);const options=t.calls[0];assert.ok(options.foregroundService.notificationTitle);assert.equal(options.showsBackgroundLocationIndicator,true);
 await t.handler({data:{locations:[{timestamp:30},{timestamp:10},{timestamp:20}]}});assert.deepEqual(t.received,[10,20,30]);assert.equal(t.calls.filter(c=>c==='flush').length,1);
 await t.service.setBackgroundRecording(false);assert.equal(t.service.backgroundRecordingEnabled(),false);assert.ok(t.calls.includes('stop'));await t.handler({data:{locations:[{timestamp:40}]}});assert.deepEqual(t.received,[10,20,30]);
});
test('headless delivery initializes recording and native registration restores the switch',async()=>{const t=await setup({registered:true});await t.handler({data:{locations:[{timestamp:10}]}});assert.deepEqual(t.received,[10]);await t.service.refreshBackgroundRecording();assert.equal(t.service.backgroundRecordingEnabled(),true);await t.handler({error:{message:'Permission revoked'}});assert.match(t.service.backgroundRecordingMessage(),/Permission revoked/)});

test('disabling while a headless batch awaits initialization discards that delivery',async()=>{let release;const t=await setup({registered:true,waitForInit:new Promise(resolve=>release=resolve)});const delivery=t.handler({data:{locations:[{timestamp:10}]}});await new Promise(resolve=>setImmediate(resolve));await t.service.setBackgroundRecording(false);release();await delivery;assert.deepEqual(t.received,[])});
