import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import {createRequire} from 'node:module';import {createStyle} from '../src/style.mjs';
const require=createRequire(import.meta.url),{expression,validateStyleMin}=createRequire(require.resolve('maplibre-gl'))('@maplibre/maplibre-gl-style-spec');
const compiled=ts.transpileModule(fs.readFileSync(new URL('../src/lakeOrientation.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
function setup(bearing=0){const context=vm.createContext({exports:{}});vm.runInContext(compiled,context);vm.runInContext(context.exports.lakeOrientationScript,context);const style=createStyle({bounds:[-180,-85,180,85],minZoom:0,maxZoom:12},'https://tiles/{z}/{x}/{y}.pbf');const layer=style.layers.find(l=>l.id==='lake-labels'),base=structuredClone(layer.layout['text-rotate']);const handlers={},writes=[];const map={getBearing:()=>bearing,getLayer:id=>style.layers.find(l=>l.id===id),getStyle:()=>style,isStyleLoaded:()=>true,on:(e,f)=>handlers[e]=f,off:(e,f)=>{if(handlers[e]===f)delete handlers[e]},setLayoutProperty:(id,key,value)=>{writes.push(value);layer.layout[key]=value}};context.installLakeOrientation(map);return{style,layer,base,writes,handlers,rotate(value){bearing=value;handlers.rotateend()},evaluate(zoom,p){const result=expression.createExpression(layer.layout['text-rotate']);assert.equal(result.result,'success',JSON.stringify(result));return result.value.evaluate({zoom},{type:1,properties:p})}}}
test('angled and horizontal lake labels stay upright for completed rotations at every compass bearing',()=>{
 const map=setup();assert.equal(map.writes.length,0,'north-up startup does not relayout');
 const lakes=[{min_zoom:13,label_angle:-69.9,label_horizontal_zoom:13},{min_zoom:10,label_angle:-85.1,label_horizontal_zoom:8.4},{min_zoom:12,label_angle:44.4,label_horizontal_zoom:17.4}];
 for(const bearing of [-180,-150,-90,-45,0,45,90,150,180]){map.rotate(bearing);assert.deepEqual(validateStyleMin(map.style),[]);for(const zoom of [10,12,13,17])for(const p of lakes){const angle=map.evaluate(zoom,p);assert.ok(Math.cos((angle-bearing)*Math.PI/180)>=-1e-7,`${bearing}/${zoom}/${p.label_angle}: ${angle}`)}}
 map.rotate(0);assert.deepEqual(map.layer.layout['text-rotate'],map.base);assert.equal(map.evaluate(12,lakes[0]),-69.9);assert.equal(map.evaluate(13,lakes[0]),0);
});
test('initial rotated camera, style replacement and cleanup do not accumulate flips',()=>{
 const map=setup(150),p={min_zoom:13,label_angle:-69.9,label_horizontal_zoom:13};assert.ok(Math.abs(map.evaluate(12,p)-110.1)<1e-6);const count=map.writes.length;map.rotate(150);assert.equal(map.writes.length,count);
 map.layer.layout['text-rotate']=structuredClone(map.base);map.handlers['style.load']();assert.ok(Math.abs(map.evaluate(12,p)-110.1)<1e-6);map.handlers.remove();assert.equal(map.handlers.rotateend,undefined);assert.equal(map.handlers['style.load'],undefined);
});
